### ISSUE TITLE
Can not get any albums or pictures any more.

### ISSUE THREAD

**Issue by wo1988818chu** [cshold/jQuery-Facebook-Photo-Selector#21]
I think it's related to access_token.

**Comment by wo1988818chu** [comment]
GOT IT!
in csphotoselector.js comment these lines:
for (var i=0; i<input.length; i++){
//if (input[i].count){
albums[albums.length] = input[i];
//}
}

**Comment by darianno** [comment]
I had the same problem, wo1988818chu solution works.
