### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by paweljedrzejczyk** [cshold/jQuery-Facebook-Photo-Selector#24]
Hi! 
Great plugin! Looking decent :)

I can confirm that the script is no longer working. I am using demo on your website.

I created brand new facebook user account to test that, every photo is publicly available, but I get the following message: "Sorry, your friend won't let us look through their photos". I have only 2 photos - profile photo which is public, and one timeline photo which is also public.

and the response from facebook is:
```javascript
FB.__globalCallbacks.fc46f937c({"data":[]});
```

Any ideas how to fix that?

**Comment by cshold** [comment]
Does it work with other accounts that have more photos?

**Comment by paweljedrzejczyk** [comment]
Unfortunately not. I've checked it on three different accounts, each of the accounts has at least two albums with photos. Does it work for you? Maybe Facebook changed something in Open Graph API recently?

**Comment by cshold** [comment]
Looks like there is some new submit process I have to do to make this public again. Working on it.

![screen shot 2015-10-02 at 11 14 23 am](https://cloud.githubusercontent.com/assets/1730309/10250068/bf5ff126-68f6-11e5-8a29-28ff27b12f20.png)

**Comment by cshold** [comment]
Looks like 5 days until things are reviewed. Sucks that this is the process for little apps like this

**Comment by paweljedrzejczyk** [comment]
The demo works now! Thanks.
